// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyp0_Vm1-kFi7C5jOqkQhzp0ixMrBn6-0',
    appId: '1:674663797926:web:772e661b8ac5f63adb5067',
    messagingSenderId: '674663797926',
    projectId: 'buyear-e477f',
    authDomain: 'buyear-e477f.firebaseapp.com',
    storageBucket: 'buyear-e477f.appspot.com',
    measurementId: 'G-HG08499MN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuHcC6Dr153uuIcfks1LU1S4dHnpIuZlI',
    appId: '1:674663797926:android:8dec36f9acab8b27db5067',
    messagingSenderId: '674663797926',
    projectId: 'buyear-e477f',
    storageBucket: 'buyear-e477f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM4o6chBohqsiqcXXxlVeQn8t3QCJ-YMA',
    appId: '1:674663797926:ios:578a277299c2c3fbdb5067',
    messagingSenderId: '674663797926',
    projectId: 'buyear-e477f',
    storageBucket: 'buyear-e477f.appspot.com',
    iosClientId: '674663797926-shikp4p908rl14jgqeoha6tpejm7uiut.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplica',
  );
}
